export const cacheLensStyles = String.raw`
.ncl-root{--ncl-bg:#ffffff;--ncl-panel:#f7f7f8;--ncl-raised:#fff;--ncl-text:#202124;--ncl-muted:#656a73;--ncl-border:#d9dce1;--ncl-accent:#1769e0;--ncl-accent-soft:#eaf2ff;--ncl-good:#16803a;--ncl-warn:#a15c00;--ncl-bad:#bd2c2c;--ncl-shadow:0 12px 42px rgba(16,24,40,.2);font-family:ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:var(--ncl-text);font-size:13px;line-height:1.4;color-scheme:light;position:fixed;z-index:2147483000}
@media(prefers-color-scheme:dark){.ncl-root[data-theme="system"]{--ncl-bg:#17181a;--ncl-panel:#202226;--ncl-raised:#191a1d;--ncl-text:#edf0f4;--ncl-muted:#a8adb7;--ncl-border:#383b42;--ncl-accent:#70a7ff;--ncl-accent-soft:#172d4d;--ncl-good:#59c778;--ncl-warn:#e6a747;--ncl-bad:#f07178;--ncl-shadow:0 12px 44px rgba(0,0,0,.55);color-scheme:dark}}
.ncl-root[data-theme="dark"]{--ncl-bg:#17181a;--ncl-panel:#202226;--ncl-raised:#191a1d;--ncl-text:#edf0f4;--ncl-muted:#a8adb7;--ncl-border:#383b42;--ncl-accent:#70a7ff;--ncl-accent-soft:#172d4d;--ncl-good:#59c778;--ncl-warn:#e6a747;--ncl-bad:#f07178;--ncl-shadow:0 12px 44px rgba(0,0,0,.55);color-scheme:dark}
.ncl-root *{box-sizing:border-box}.ncl-root button,.ncl-root input,.ncl-root select{font:inherit}.ncl-root button{color:inherit}.ncl-root button:focus-visible,.ncl-root input:focus-visible,.ncl-root select:focus-visible{outline:2px solid var(--ncl-accent);outline-offset:2px}
.ncl-root[data-position="bottom-right"]{right:16px;bottom:16px}.ncl-root[data-position="bottom-left"]{left:16px;bottom:16px}
.ncl-launcher{height:34px;padding:0 11px;border:1px solid var(--ncl-border);border-radius:7px;background:var(--ncl-bg);box-shadow:0 3px 14px rgba(0,0,0,.15);display:flex;align-items:center;gap:7px;cursor:pointer;font-weight:600}.ncl-launcher:hover{background:var(--ncl-panel)}.ncl-activity{width:7px;height:7px;border-radius:50%;background:var(--ncl-muted)}.ncl-activity[data-active="true"]{background:var(--ncl-good);box-shadow:0 0 0 3px color-mix(in srgb,var(--ncl-good) 18%,transparent)}
.ncl-panel{width:min(920px,calc(100vw - 32px));height:min(650px,calc(100vh - 32px));background:var(--ncl-bg);border:1px solid var(--ncl-border);border-radius:9px;box-shadow:var(--ncl-shadow);overflow:hidden;display:grid;grid-template-rows:43px 35px minmax(0,1fr)}
.ncl-titlebar{display:flex;align-items:center;gap:9px;padding:0 10px;border-bottom:1px solid var(--ncl-border);background:var(--ncl-panel)}.ncl-mark{width:10px;height:10px;border:2px solid var(--ncl-accent);border-radius:50%}.ncl-title{font-weight:650}.ncl-subtitle{color:var(--ncl-muted);font-size:11px}.ncl-spacer{flex:1}.ncl-icon-button{width:28px;height:28px;border:0;border-radius:5px;background:transparent;display:grid;place-items:center;cursor:pointer}.ncl-icon-button:hover{background:color-mix(in srgb,var(--ncl-text) 8%,transparent)}
.ncl-tabs{display:flex;align-items:stretch;padding:0 7px;border-bottom:1px solid var(--ncl-border);background:var(--ncl-raised);overflow:auto}.ncl-tab{border:0;border-bottom:2px solid transparent;background:transparent;padding:0 10px;cursor:pointer;color:var(--ncl-muted);white-space:nowrap}.ncl-tab[aria-selected="true"]{border-bottom-color:var(--ncl-accent);color:var(--ncl-text);font-weight:600}
.ncl-content{min-height:0;overflow:auto;background:var(--ncl-bg)}.ncl-section{padding:14px}.ncl-section-heading{font-size:12px;text-transform:uppercase;letter-spacing:.05em;color:var(--ncl-muted);margin:0 0 9px}.ncl-empty{min-height:220px;display:grid;place-content:center;text-align:center;color:var(--ncl-muted);padding:24px}.ncl-empty strong{color:var(--ncl-text);font-size:14px;margin-bottom:4px}
.ncl-error{margin:10px;padding:9px 11px;border:1px solid color-mix(in srgb,var(--ncl-bad) 50%,var(--ncl-border));background:color-mix(in srgb,var(--ncl-bad) 8%,var(--ncl-bg));color:var(--ncl-bad);border-radius:5px}
.ncl-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border:1px solid var(--ncl-border);border-radius:6px;overflow:hidden;margin-bottom:16px}.ncl-metric{padding:10px 12px;background:var(--ncl-raised);border-right:1px solid var(--ncl-border);border-bottom:1px solid var(--ncl-border)}.ncl-metric:nth-child(4n){border-right:0}.ncl-metric:nth-last-child(-n+4){border-bottom:0}.ncl-metric-label{color:var(--ncl-muted);font-size:11px}.ncl-metric-value{font-size:20px;font-variant-numeric:tabular-nums;margin-top:2px}
.ncl-toolbar{display:flex;gap:7px;align-items:center;margin-bottom:10px;flex-wrap:wrap}.ncl-input,.ncl-select{height:30px;border:1px solid var(--ncl-border);border-radius:5px;background:var(--ncl-raised);color:var(--ncl-text);padding:0 8px}.ncl-input{min-width:220px;flex:1}.ncl-button{height:30px;border:1px solid var(--ncl-border);border-radius:5px;background:var(--ncl-raised);padding:0 9px;cursor:pointer}.ncl-button:hover{background:var(--ncl-panel)}.ncl-button:disabled{opacity:.5;cursor:not-allowed}.ncl-button-primary{background:var(--ncl-accent-soft);border-color:color-mix(in srgb,var(--ncl-accent) 40%,var(--ncl-border));color:var(--ncl-accent)}
.ncl-table-wrap{border:1px solid var(--ncl-border);border-radius:6px;overflow:auto}.ncl-table{width:100%;border-collapse:collapse;font-size:12px}.ncl-table th{position:sticky;top:0;background:var(--ncl-panel);z-index:1;text-align:left;color:var(--ncl-muted);font-weight:600;padding:7px 9px;border-bottom:1px solid var(--ncl-border);white-space:nowrap}.ncl-table td{padding:7px 9px;border-bottom:1px solid var(--ncl-border);vertical-align:middle}.ncl-table tr:last-child td{border-bottom:0}.ncl-table tbody tr[data-clickable="true"]{cursor:pointer}.ncl-table tbody tr[data-clickable="true"]:hover,.ncl-table tbody tr[aria-selected="true"]{background:var(--ncl-accent-soft)}.ncl-id{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:11px}.ncl-num{font-variant-numeric:tabular-nums;text-align:right}.ncl-time{white-space:nowrap;color:var(--ncl-muted)}
.ncl-status{display:inline-flex;align-items:center;gap:5px;text-transform:capitalize}.ncl-status::before{content:"";width:6px;height:6px;border-radius:50%;background:var(--ncl-muted)}.ncl-status[data-status="fresh"]::before{background:var(--ncl-good)}.ncl-status[data-status="stale"]::before{background:var(--ncl-warn)}.ncl-status[data-status="expired"]::before,.ncl-status[data-status="invalidated"]::before{background:var(--ncl-bad)}
.ncl-chip{display:inline-flex;align-items:center;max-width:190px;padding:1px 6px;border:1px solid var(--ncl-border);border-radius:9px;background:var(--ncl-panel);margin:1px 3px 1px 0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:11px}.ncl-chip-button{cursor:pointer;color:var(--ncl-accent)}
.ncl-split{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:10px}.ncl-details{border:1px solid var(--ncl-border);border-radius:6px;background:var(--ncl-raised);padding:11px;position:sticky;top:0;align-self:start}.ncl-details h3{font:600 12px ui-monospace,SFMono-Regular,Consolas,monospace;margin:0 0 12px;overflow-wrap:anywhere}.ncl-dl{display:grid;grid-template-columns:90px minmax(0,1fr);gap:7px;margin:0}.ncl-dl dt{color:var(--ncl-muted)}.ncl-dl dd{margin:0;min-width:0;overflow-wrap:anywhere}
.ncl-event-type{font:600 11px ui-monospace,SFMono-Regular,Consolas,monospace}.ncl-event-type[data-kind="HIT"],.ncl-event-type[data-kind="SET"]{color:var(--ncl-good)}.ncl-event-type[data-kind="MISS"],.ncl-event-type[data-kind="ERROR"]{color:var(--ncl-bad)}.ncl-event-type[data-kind="INVALIDATE"],.ncl-event-type[data-kind="REVALIDATE"],.ncl-event-type[data-kind="STALE"]{color:var(--ncl-warn)}
.ncl-tag-list{display:grid;gap:7px}.ncl-tag-row{display:grid;grid-template-columns:minmax(120px,1fr) 90px 100px auto;gap:10px;align-items:center;padding:8px 9px;border:1px solid var(--ncl-border);border-radius:6px;background:var(--ncl-raised)}
.ncl-graph{display:grid;grid-template-columns:minmax(120px,1fr) 28px minmax(140px,1fr) 28px minmax(160px,1fr);gap:7px;align-items:start}.ncl-graph-column{display:grid;gap:7px}.ncl-graph-arrow{display:grid;place-items:center;color:var(--ncl-muted);min-height:34px}.ncl-node{border:1px solid var(--ncl-border);border-radius:5px;padding:7px 8px;background:var(--ncl-raised);overflow-wrap:anywhere}.ncl-node button{border:0;background:transparent;padding:0;color:var(--ncl-accent);cursor:pointer;text-align:left}.ncl-node-label{font-size:10px;text-transform:uppercase;color:var(--ncl-muted);margin-bottom:2px}
.ncl-diagnostics{display:grid;gap:8px}.ncl-diagnostic{border:1px solid var(--ncl-border);border-left:3px solid var(--ncl-accent);border-radius:5px;padding:9px 10px;background:var(--ncl-raised)}.ncl-diagnostic[data-severity="warning"]{border-left-color:var(--ncl-warn)}.ncl-diagnostic-title{font-weight:600;margin-bottom:2px}.ncl-diagnostic-description{color:var(--ncl-muted)}
.ncl-live{display:flex;align-items:center;gap:5px;color:var(--ncl-muted);font-size:11px}.ncl-live::before{content:"";width:6px;height:6px;border-radius:50%;background:var(--ncl-good)}
@media(max-width:720px){.ncl-panel{height:calc(100vh - 24px);width:calc(100vw - 24px)}.ncl-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.ncl-metric:nth-child(2n){border-right:0}.ncl-metric:nth-last-child(-n+4){border-bottom:1px solid var(--ncl-border)}.ncl-metric:nth-last-child(-n+2){border-bottom:0}.ncl-split{grid-template-columns:1fr}.ncl-details{position:static}.ncl-tag-row{grid-template-columns:1fr auto}.ncl-tag-secondary{display:none}.ncl-graph{grid-template-columns:1fr}.ncl-graph-arrow{min-height:auto;transform:rotate(90deg)}}
@media(prefers-reduced-motion:reduce){.ncl-root *{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
`
